export const TEAM_MANAGERS_DETAILS = [
{
    name: "Manish S",
        img: "/images/teamImages/manish.jpg",
    imgWebp: "/images/teamImages/manish.webp",
    linkedin: "https://www.linkedin.com/in/manish-s-89ab80243/",
    facebook: "https://www.facebook.com/profile.php?id=100075516520476",
    mail: "manish.teamkartkgp@gmail.com",
    designation1: "Team Leader",
    designation2: "Head of Mechanical Systems",
    designation3: "Chassis Head",
    manager: true,
},
{
    name: "Vedant Dave",
        img: "/images/teamImages/vedant.jpg",
    imgWebp: "/images/teamImages/vedant.webp",
    linkedin: "https://www.linkedin.com/in/vedant-santosh-dave-416175224/",
    facebook: "https://www.facebook.com/profile.php?id=100074874957923",
    mail: "vedant.teamkartkgp@gmail.com",
    designation1: "Deputy Team Leader",
    designation2: "Electronics Head",
    designation3: "",
    manager: true,
},
{
    name: "Harsh Kumar",
    img: "/images/teamImages/harsh.jpg",
    imgWebp: "/images/teamImages/harsh.webp",
    linkedin: "https://www.linkedin.com/in/harsh-kumar-bhadhotia-204a88203/",
    facebook: "https://www.facebook.com/profile.php?id=100013802584124",
    mail: "harshkumar.teamkartkgp@gmail.com",
    designation1: "Finance Head",
    designation2: "Corporate and Public Relations Head",
    designation3: "",
    manager: true,
},

]


export const TEAM_HEADS_DETAILS = [

    {
        name: "Avi Saraf",
        img: "/images/teamImages/avi.jpg",
        imgWebp: "/images/teamImages/avi.webp",
        linkedin: "https://www.linkedin.com/in/avi-saraf-0b62851b6/",
        facebook: "https://www.facebook.com/avi.saraf.90",
        mail: "avi.teamkartkgp@gmail.com",
        designation1: "Electric Powertrain Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Aaronyak Dewanji",
        img: "/images/teamImages/aaronyak.jpg",
        imgWebp: "/images/teamImages/aaronyak.webp",
        linkedin: "https://www.linkedin.com/in/aaronyak-dewanji-b49a60238/",
        facebook: "https://www.facebook.com/profile.php?id=100074065076841",
        mail: "aaronyak.teamkartkgp@gmail.com",
        designation1: "Battery Management System Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Mayukh S Saha",
        img: "/images/teamImages/mayukh.jpg",
        imgWebp: "/images/teamImages/mayukh.webp",
        linkedin: "https://www.linkedin.com/in/mayukh-shubhra-saha-668b07243/",
        facebook: "https://www.facebook.com/mayukh.s.saha.404",
        mail: "mayukh.teamkartkgp@gmail.com",
        designation1: "Low Voltage Systems Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Sandeep Varma",
        img: "/images/teamImages/sandeep.jpg",
        imgWebp: "/images/teamImages/sandeep.webp",
        linkedin: "https://www.linkedin.com/in/sndpvrmah/",
        facebook: "https://www.facebook.com/gysndp1",
        mail: "sandeep.teamkartkgp@gmail.com",
        designation1: "Data Acquisition System Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Gollapalli Dheeraj",
        img: "/images/teamImages/dheeraj.jpg",
        imgWebp: "/images/teamImages/dheeraj.webp",
        linkedin: "https://www.linkedin.com/in/dheeraj-gollapalli-369b35244/",
        facebook: "https://www.facebook.com/profile.php?id=100075741466209",
        mail: "dheeraj.teamkartkgp@gmail.com",
        designation1: "Drivetrain & Thermals Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Om Talreja",
        img: "/images/teamImages/om.jpg",
        imgWebp: "/images/teamImages/om.webp",
        linkedin: "https://www.linkedin.com/in/om-talreja/",
        facebook: "https://www.facebook.com/profile.php?id=100075560325183",
        mail: "om.teamkartkgp@gmail.com",
        designation1: "Drivetrain & Thermals Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Mohammed Raihaan",
        img: "/images/teamImages/raihaan.jpg",
        imgWebp: "/images/teamImages/raihaan.webp",
        linkedin: "https://www.linkedin.com/in/mohammed-raihaan/",
        facebook: "https://www.facebook.com/mohammed.raihaan.94",
        mail: "raihaan.teamkartkgp@gmail.com",
        designation1: "Aerodynamics & Composites Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Debojyoti Roy",
        img: "/images/teamImages/debojyoti.jpg",
        imgWebp: "/images/teamImages/debojyoti.webp",
        linkedin: "https://www.linkedin.com/in/debojyoti-roy-bb5329233/",
        facebook: "https://www.facebook.com/debojyotiroy2002",
        mail: "debojyoti.teamkartkgp@gmail.com",
        designation1: "Aerodynamics & Composites Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Shaikh Amaanur Rahman",
        img: "/images/teamImages/amaanur.jpg",
        imgWebp: "/images/teamImages/amaanur.webp",
        linkedin: "https://www.linkedin.com/in/shaikh-amaanur-rahman-953476239/",
        facebook: "https://www.facebook.com/profile.php?id=100075713804559",
        mail: "amaanur.teamkartkgp@gmail.com",
        designation1: "Drivetrain & Thermals Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Sayantan Sarkar",
        img: "/images/teamImages/sayantan.jpg",
        imgWebp: "/images/teamImages/sayantan.webp",
        linkedin: "https://www.linkedin.com/in/sayantan-sarkar-a535b422a/",
        facebook: "https://www.facebook.com/profile.php?id=100075404450770",
        mail: "sayantan.teamkartkgp@gmail.com",
        designation1: "Suspension, Steering & Brakes Head",
        designation2: "Media Head",
        designation3: "",
        manager: false,
    },
    {
        name: "Dillip Dibyajyoti Dash",
        img: "/images/teamImages/dilip.jpg",
        imgWebp: "/images/teamImages/dilip.webp",
        linkedin: "https://www.linkedin.com/in/dillip-dibyajyoti-dash-b628a7240/",
        facebook: "",
        mail: "dilip.teamkartkgp@gmail.com",
        designation1: "Low Voltage Systems Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Harsh Kumar",
        img: "/images/teamImages/harshkumar.jpg",
        imgWebp: "/images/teamImages/harshkumar.webp",
        linkedin: "",
        facebook: "",
        mail: "harshaero.teamkartkgp@gmail.com",
        designation1: "Data Acquisition System Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Kokula Selvan J",
        img: "/images/teamImages/kokula.jpg",
        imgWebp: "/images/teamImages/kokula.webp",
        linkedin: "https://www.linkedin.com/in/kokula-selvan-8a437b248/",
        facebook: "https://www.facebook.com/profile.php?id=100074420423605",
        mail: "kokula.teamkartkgp@gmail.com",
        designation1: "Chassis Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Maria Helenaa Manickam",
        img: "/images/teamImages/maria.jpg",
        imgWebp: "/images/teamImages/maria.webp",
        linkedin: "https://www.linkedin.com/in/maria-helenaa-9a0490230/",
        facebook: "https://www.facebook.com/helenavrm",
        mail: "maria.teamkartkgp@gmail.com",
        designation1: "Suspension, Steering & Brakes Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Salil Lokhande",
        img: "/images/teamImages/salil.jpg",
        imgWebp: "/images/teamImages/salil.webp",
        linkedin: "https://www.linkedin.com/in/salil-lokhande-403921248/",
        facebook: "https://www.facebook.com/profile.php?id=100080061060883",
        mail: "salil.teamkartkgp@gmail.com",
        designation1: "Suspension, Steering & Brakes Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "R S Thiruvignesh",
        img: "/images/teamImages/thiruvignesh.jpg",
        imgWebp: "/images/teamImages/thiruvignesh.webp",
        linkedin: "https://www.linkedin.com/in/r-s-thiruvignesh-224172228/",
        facebook: "https://www.facebook.com/thiru.vignesh.946",
        mail: "thiru.teamkartkgp@gmail.com",
        designation1: "Static Events Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Swapnil Sharma",
        img: "/images/teamImages/swapnil.jpg",
        imgWebp: "/images/teamImages/swapnil.webp",
        linkedin: "",
        facebook: "",
        mail: "swapnil.teamkartkgp@gmail.com",
        designation1: "Battery Management System Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
    {
        name: "Vigneswaran S",
        img: "/images/teamImages/vigneswaran.jpg",
        imgWebp: "/images/teamImages/vigneswaran.webp",
        linkedin: "https://www.linkedin.com/in/vigneswaran-s-536575227/",
        facebook: "https://www.facebook.com/profile.php?id=100075757830008",
        mail: "vigneswaran.teamkartkgp@gmail.com",
        designation1: "Aerodynamics & Composites Head",
        designation2: "",
        designation3: "",
        manager: false,
    },
]

export const TEAM_MEMBERS_DETAILS2 = {
    "CPR & Media": ["Aniket Thakare", "Himanshu Singh", "K Aniruddha Bhardwaj", "Pritish Saha", "Shubham Pingale", "Thejaswini Devakumar", "Vaibhav K"],
    "Chassis": ["Anirudha Wasnik", "Ayush Saraykar"],
    "Suspension, Steering and Brakes": ["Dev Bhatia","Samarth Kiran Rane"],
    "Aerodynamics and Composites" : ["Kunal Kathuria", "Disha Uppuluri"],
    "Powertrain": ["Himanshu Sahu", "Jaya Shankar", "Sarthak Tonk", "Srinjoy Ganguly"],
    "High Voltage": ["Aakarsh A", "Kislay Arya", "Oishik Nandi"],
    "Low Voltage": ["Sanskar Agarwal", "Deep Ghosh"],
    "DAQ": ["Abhinandh", "Roctotpal Sandilya"]
}

